import type {
  Vendor,
  Customer,
  Product,
  Order,
  Payment,
  CommissionRule,
  Coupon,
  Category,
  CmsPage,
  Banner,
  Role,
  Permission,
  ActivityLog,
  ChartPoint,
  KpiMetric,
} from "@/types";

export const dashboardKpis: KpiMetric[] = [
  { label: "Total Revenue", value: 2847650, change: 12.4, trend: "up", format: "currency" },
  { label: "Marketplace GMV", value: 8924300, change: 8.7, trend: "up", format: "currency" },
  { label: "Total Orders", value: 18492, change: 5.2, trend: "up", format: "number" },
  { label: "Active Vendors", value: 1247, change: 3.1, trend: "up", format: "number" },
  { label: "Total Customers", value: 45820, change: 9.8, trend: "up", format: "number" },
  { label: "Pending Approvals", value: 86, change: -4.2, trend: "down", format: "number" },
];

export const revenueChart: ChartPoint[] = [
  { name: "Jan", value: 420000, secondary: 380000 },
  { name: "Feb", value: 480000, secondary: 410000 },
  { name: "Mar", value: 520000, secondary: 460000 },
  { name: "Apr", value: 490000, secondary: 440000 },
  { name: "May", value: 610000, secondary: 520000 },
  { name: "Jun", value: 680000, secondary: 580000 },
  { name: "Jul", value: 720000, secondary: 640000 },
  { name: "Aug", value: 690000, secondary: 610000 },
  { name: "Sep", value: 750000, secondary: 670000 },
  { name: "Oct", value: 820000, secondary: 720000 },
  { name: "Nov", value: 880000, secondary: 790000 },
  { name: "Dec", value: 940000, secondary: 850000 },
];

export const orderTrends: ChartPoint[] = [
  { name: "Mon", value: 420 },
  { name: "Tue", value: 510 },
  { name: "Wed", value: 480 },
  { name: "Thu", value: 620 },
  { name: "Fri", value: 710 },
  { name: "Sat", value: 890 },
  { name: "Sun", value: 650 },
];

export const vendorPerformance: ChartPoint[] = [
  { name: "TechHub", value: 284000 },
  { name: "StyleCo", value: 198000 },
  { name: "HomeNest", value: 176000 },
  { name: "FitLife", value: 142000 },
  { name: "BookWorld", value: 98000 },
];

export const customerGrowth: ChartPoint[] = [
  { name: "Jan", value: 3200 },
  { name: "Feb", value: 3800 },
  { name: "Mar", value: 4100 },
  { name: "Apr", value: 3900 },
  { name: "May", value: 4600 },
  { name: "Jun", value: 5200 },
  { name: "Jul", value: 5800 },
];

export const productSales: ChartPoint[] = [
  { name: "Electronics", value: 35 },
  { name: "Fashion", value: 25 },
  { name: "Home", value: 18 },
  { name: "Sports", value: 12 },
  { name: "Books", value: 10 },
];

export const vendors: Vendor[] = [
  {
    id: "v1",
    name: "James Carter",
    storeName: "TechHub Store",
    email: "james@techhub.com",
    phone: "+1 555-0101",
    status: "active",
    registrationDate: "2024-01-15",
    sales: 284000,
    products: 156,
    orders: 2340,
    commission: 12,
    rating: 4.8,
    description: "Premium electronics and gadgets marketplace store.",
    address: "120 Market St, San Francisco, CA",
    category: "Electronics",
  },
  {
    id: "v2",
    name: "Sarah Mitchell",
    storeName: "StyleCo Fashion",
    email: "sarah@styleco.com",
    phone: "+1 555-0102",
    status: "active",
    registrationDate: "2024-02-20",
    sales: 198000,
    products: 320,
    orders: 1890,
    commission: 15,
    rating: 4.6,
    description: "Contemporary fashion for modern lifestyles.",
    address: "88 Fashion Ave, New York, NY",
    category: "Fashion",
  },
  {
    id: "v3",
    name: "Michael Chen",
    storeName: "HomeNest Living",
    email: "michael@homenest.com",
    phone: "+1 555-0103",
    status: "pending",
    registrationDate: "2025-06-10",
    sales: 0,
    products: 24,
    orders: 0,
    commission: 10,
    rating: 0,
    description: "Home décor and furniture essentials.",
    address: "45 Oak Blvd, Austin, TX",
    category: "Home",
  },
  {
    id: "v4",
    name: "Emily Rodriguez",
    storeName: "FitLife Gear",
    email: "emily@fitlife.com",
    phone: "+1 555-0104",
    status: "active",
    registrationDate: "2024-03-08",
    sales: 142000,
    products: 89,
    orders: 1120,
    commission: 12,
    rating: 4.7,
    description: "Sports and fitness equipment specialists.",
    address: "210 Sport Way, Denver, CO",
    category: "Sports",
  },
  {
    id: "v5",
    name: "David Park",
    storeName: "BookWorld",
    email: "david@bookworld.com",
    phone: "+1 555-0105",
    status: "suspended",
    registrationDate: "2024-04-12",
    sales: 98000,
    products: 450,
    orders: 980,
    commission: 8,
    rating: 4.2,
    description: "Books, magazines, and educational materials.",
    address: "15 Library Ln, Seattle, WA",
    category: "Books",
  },
  {
    id: "v6",
    name: "Lisa Thompson",
    storeName: "BeautyBox",
    email: "lisa@beautybox.com",
    phone: "+1 555-0106",
    status: "approved",
    registrationDate: "2025-05-22",
    sales: 45000,
    products: 67,
    orders: 340,
    commission: 14,
    rating: 4.5,
    description: "Beauty and personal care products.",
    address: "99 Glow St, Miami, FL",
    category: "Beauty",
  },
  {
    id: "v7",
    name: "Robert Kim",
    storeName: "GadgetPro",
    email: "robert@gadgetpro.com",
    phone: "+1 555-0107",
    status: "rejected",
    registrationDate: "2025-06-01",
    sales: 0,
    products: 12,
    orders: 0,
    commission: 12,
    rating: 0,
    description: "Consumer electronics accessories.",
    address: "77 Circuit Rd, Portland, OR",
    category: "Electronics",
  },
  {
    id: "v8",
    name: "Amanda Foster",
    storeName: "PetPalace",
    email: "amanda@petpalace.com",
    phone: "+1 555-0108",
    status: "active",
    registrationDate: "2024-07-18",
    sales: 76000,
    products: 145,
    orders: 890,
    commission: 10,
    rating: 4.9,
    description: "Premium pet supplies and accessories.",
    address: "33 Paw Ave, Chicago, IL",
    category: "Pets",
  },
];

export const customers: Customer[] = [
  {
    id: "c1",
    name: "Alice Johnson",
    email: "alice.j@email.com",
    phone: "+1 555-1001",
    status: "active",
    joinDate: "2024-01-10",
    orders: 24,
    totalSpent: 4850,
    lastOrder: "2025-06-28",
    address: "12 Maple St, Boston, MA",
  },
  {
    id: "c2",
    name: "Brian Smith",
    email: "brian.s@email.com",
    phone: "+1 555-1002",
    status: "active",
    joinDate: "2024-02-14",
    orders: 18,
    totalSpent: 3200,
    lastOrder: "2025-06-25",
    address: "45 Pine Rd, Dallas, TX",
  },
  {
    id: "c3",
    name: "Carol White",
    email: "carol.w@email.com",
    phone: "+1 555-1003",
    status: "blocked",
    joinDate: "2024-03-01",
    orders: 5,
    totalSpent: 890,
    lastOrder: "2025-01-15",
    address: "78 Cedar Ave, Phoenix, AZ",
  },
  {
    id: "c4",
    name: "Daniel Lee",
    email: "daniel.l@email.com",
    phone: "+1 555-1004",
    status: "active",
    joinDate: "2024-04-20",
    orders: 42,
    totalSpent: 12400,
    lastOrder: "2025-06-30",
    address: "90 Birch Blvd, Atlanta, GA",
  },
  {
    id: "c5",
    name: "Eva Martinez",
    email: "eva.m@email.com",
    phone: "+1 555-1005",
    status: "inactive",
    joinDate: "2024-05-05",
    orders: 2,
    totalSpent: 150,
    lastOrder: "2024-08-12",
    address: "21 Elm Ct, Nashville, TN",
  },
  {
    id: "c6",
    name: "Frank Wilson",
    email: "frank.w@email.com",
    phone: "+1 555-1006",
    status: "active",
    joinDate: "2024-06-18",
    orders: 31,
    totalSpent: 7650,
    lastOrder: "2025-06-29",
    address: "56 Willow Dr, Minneapolis, MN",
  },
  {
    id: "c7",
    name: "Grace Kim",
    email: "grace.k@email.com",
    phone: "+1 555-1007",
    status: "active",
    joinDate: "2024-08-22",
    orders: 15,
    totalSpent: 2890,
    lastOrder: "2025-06-20",
    address: "34 Spruce Way, Portland, OR",
  },
  {
    id: "c8",
    name: "Henry Brown",
    email: "henry.b@email.com",
    phone: "+1 555-1008",
    status: "active",
    joinDate: "2024-09-10",
    orders: 9,
    totalSpent: 1560,
    lastOrder: "2025-06-15",
    address: "67 Aspen Ln, Salt Lake City, UT",
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Wireless Noise-Canceling Headphones",
    sku: "TECH-WH-001",
    vendorId: "v1",
    vendorName: "TechHub Store",
    category: "Electronics",
    price: 299,
    stock: 145,
    status: "approved",
    submittedAt: "2024-11-01",
    description: "Premium over-ear headphones with active noise cancellation.",
    sales: 890,
  },
  {
    id: "p2",
    name: "Organic Cotton Summer Dress",
    sku: "FASH-DR-042",
    vendorId: "v2",
    vendorName: "StyleCo Fashion",
    category: "Fashion",
    price: 89,
    stock: 230,
    status: "approved",
    submittedAt: "2024-12-15",
    description: "Lightweight organic cotton dress for summer.",
    sales: 456,
  },
  {
    id: "p3",
    name: "Smart Home Hub Pro",
    sku: "TECH-SH-015",
    vendorId: "v1",
    vendorName: "TechHub Store",
    category: "Electronics",
    price: 149,
    stock: 80,
    status: "pending",
    submittedAt: "2025-06-25",
    description: "Central smart home control hub with voice assistant.",
    sales: 0,
  },
  {
    id: "p4",
    name: "Yoga Mat Premium",
    sku: "SPRT-YM-008",
    vendorId: "v4",
    vendorName: "FitLife Gear",
    category: "Sports",
    price: 45,
    stock: 500,
    status: "approved",
    submittedAt: "2025-01-10",
    description: "Non-slip eco-friendly yoga mat.",
    sales: 1200,
  },
  {
    id: "p5",
    name: "Ceramic Dinnerware Set",
    sku: "HOME-DW-021",
    vendorId: "v3",
    vendorName: "HomeNest Living",
    category: "Home",
    price: 120,
    stock: 60,
    status: "pending",
    submittedAt: "2025-06-28",
    description: "12-piece ceramic dinnerware set in matte finish.",
    sales: 0,
  },
  {
    id: "p6",
    name: "Running Shoes Elite",
    sku: "SPRT-RS-033",
    vendorId: "v4",
    vendorName: "FitLife Gear",
    category: "Sports",
    price: 159,
    stock: 200,
    status: "rejected",
    submittedAt: "2025-06-20",
    description: "Professional running shoes with carbon plate.",
    sales: 0,
  },
  {
    id: "p7",
    name: "Leather Crossbody Bag",
    sku: "FASH-BG-019",
    vendorId: "v2",
    vendorName: "StyleCo Fashion",
    category: "Fashion",
    price: 175,
    stock: 45,
    status: "approved",
    submittedAt: "2025-02-01",
    description: "Genuine leather crossbody bag.",
    sales: 234,
  },
  {
    id: "p8",
    name: "Pet Orthopedic Bed",
    sku: "PET-BD-005",
    vendorId: "v8",
    vendorName: "PetPalace",
    category: "Pets",
    price: 79,
    stock: 110,
    status: "approved",
    submittedAt: "2025-03-15",
    description: "Memory foam orthopedic pet bed.",
    sales: 567,
  },
];

export const orders: Order[] = [
  {
    id: "o1",
    orderNumber: "ORD-2025-88421",
    customerId: "c1",
    customerName: "Alice Johnson",
    vendorId: "v1",
    vendorName: "TechHub Store",
    status: "delivered",
    paymentStatus: "completed",
    total: 299,
    items: 1,
    createdAt: "2025-06-20T10:30:00",
    shippingStatus: "Delivered",
    trackingNumber: "TRK-88421001",
  },
  {
    id: "o2",
    orderNumber: "ORD-2025-88422",
    customerId: "c4",
    customerName: "Daniel Lee",
    vendorId: "v2",
    vendorName: "StyleCo Fashion",
    status: "shipped",
    paymentStatus: "completed",
    total: 264,
    items: 3,
    createdAt: "2025-06-25T14:15:00",
    shippingStatus: "In Transit",
    trackingNumber: "TRK-88422002",
  },
  {
    id: "o3",
    orderNumber: "ORD-2025-88423",
    customerId: "c6",
    customerName: "Frank Wilson",
    vendorId: "v4",
    vendorName: "FitLife Gear",
    status: "processing",
    paymentStatus: "completed",
    total: 204,
    items: 2,
    createdAt: "2025-06-28T09:00:00",
    shippingStatus: "Preparing",
  },
  {
    id: "o4",
    orderNumber: "ORD-2025-88424",
    customerId: "c2",
    customerName: "Brian Smith",
    vendorId: "v8",
    vendorName: "PetPalace",
    status: "pending",
    paymentStatus: "pending",
    total: 79,
    items: 1,
    createdAt: "2025-06-30T16:45:00",
  },
  {
    id: "o5",
    orderNumber: "ORD-2025-88425",
    customerId: "c7",
    customerName: "Grace Kim",
    vendorId: "v1",
    vendorName: "TechHub Store",
    status: "cancelled",
    paymentStatus: "refunded",
    total: 149,
    items: 1,
    createdAt: "2025-06-18T11:20:00",
  },
  {
    id: "o6",
    orderNumber: "ORD-2025-88426",
    customerId: "c4",
    customerName: "Daniel Lee",
    vendorId: "v2",
    vendorName: "StyleCo Fashion",
    status: "refunded",
    paymentStatus: "refunded",
    total: 89,
    items: 1,
    createdAt: "2025-06-15T08:30:00",
  },
  {
    id: "o7",
    orderNumber: "ORD-2025-88427",
    customerId: "c8",
    customerName: "Henry Brown",
    vendorId: "v4",
    vendorName: "FitLife Gear",
    status: "confirmed",
    paymentStatus: "completed",
    total: 45,
    items: 1,
    createdAt: "2025-06-29T13:00:00",
  },
  {
    id: "o8",
    orderNumber: "ORD-2025-88428",
    customerId: "c1",
    customerName: "Alice Johnson",
    vendorId: "v8",
    vendorName: "PetPalace",
    status: "delivered",
    paymentStatus: "completed",
    total: 158,
    items: 2,
    createdAt: "2025-06-10T17:30:00",
    shippingStatus: "Delivered",
    trackingNumber: "TRK-88428008",
  },
];

export const payments: Payment[] = [
  {
    id: "pay1",
    transactionId: "TXN-99001",
    orderId: "o1",
    vendorId: "v1",
    vendorName: "TechHub Store",
    amount: 299,
    commission: 35.88,
    vendorPayout: 263.12,
    status: "completed",
    method: "Credit Card",
    createdAt: "2025-06-20T10:31:00",
  },
  {
    id: "pay2",
    transactionId: "TXN-99002",
    orderId: "o2",
    vendorId: "v2",
    vendorName: "StyleCo Fashion",
    amount: 264,
    commission: 39.6,
    vendorPayout: 224.4,
    status: "completed",
    method: "PayPal",
    createdAt: "2025-06-25T14:16:00",
  },
  {
    id: "pay3",
    transactionId: "TXN-99003",
    orderId: "o3",
    vendorId: "v4",
    vendorName: "FitLife Gear",
    amount: 204,
    commission: 24.48,
    vendorPayout: 179.52,
    status: "completed",
    method: "Credit Card",
    createdAt: "2025-06-28T09:01:00",
  },
  {
    id: "pay4",
    transactionId: "TXN-99004",
    orderId: "o4",
    vendorId: "v8",
    vendorName: "PetPalace",
    amount: 79,
    commission: 7.9,
    vendorPayout: 71.1,
    status: "pending",
    method: "Bank Transfer",
    createdAt: "2025-06-30T16:46:00",
  },
  {
    id: "pay5",
    transactionId: "TXN-99005",
    orderId: "o5",
    vendorId: "v1",
    vendorName: "TechHub Store",
    amount: 149,
    commission: 17.88,
    vendorPayout: 0,
    status: "refunded",
    method: "Credit Card",
    createdAt: "2025-06-18T11:21:00",
  },
  {
    id: "pay6",
    transactionId: "TXN-99006",
    orderId: "o7",
    vendorId: "v4",
    vendorName: "FitLife Gear",
    amount: 45,
    commission: 5.4,
    vendorPayout: 39.6,
    status: "completed",
    method: "Apple Pay",
    createdAt: "2025-06-29T13:01:00",
  },
];

export const commissionRules: CommissionRule[] = [
  {
    id: "cr1",
    name: "Electronics Standard",
    category: "Electronics",
    percentage: 12,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "cr2",
    name: "Fashion Premium",
    category: "Fashion",
    percentage: 15,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "cr3",
    name: "Home & Living",
    category: "Home",
    percentage: 10,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "cr4",
    name: "Sports Equipment",
    category: "Sports",
    percentage: 12,
    active: true,
    createdAt: "2024-02-15",
  },
  {
    id: "cr5",
    name: "Books & Media",
    category: "Books",
    percentage: 8,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "cr6",
    name: "Beauty & Care",
    category: "Beauty",
    percentage: 14,
    active: false,
    createdAt: "2024-03-01",
  },
];

export const coupons: Coupon[] = [
  {
    id: "cp1",
    code: "SUMMER25",
    type: "percentage",
    value: 25,
    usageLimit: 1000,
    usedCount: 342,
    status: "active",
    startsAt: "2025-06-01",
    expiresAt: "2025-08-31",
  },
  {
    id: "cp2",
    code: "WELCOME10",
    type: "fixed",
    value: 10,
    usageLimit: 5000,
    usedCount: 2100,
    status: "active",
    startsAt: "2025-01-01",
    expiresAt: "2025-12-31",
  },
  {
    id: "cp3",
    code: "FREESHIP",
    type: "free_shipping",
    value: 0,
    usageLimit: 2000,
    usedCount: 890,
    status: "active",
    startsAt: "2025-05-01",
    expiresAt: "2025-07-31",
  },
  {
    id: "cp4",
    code: "FLASH50",
    type: "percentage",
    value: 50,
    usageLimit: 100,
    usedCount: 100,
    status: "expired",
    startsAt: "2025-05-01",
    expiresAt: "2025-05-03",
  },
  {
    id: "cp5",
    code: "VENDOR15",
    type: "percentage",
    value: 15,
    usageLimit: 500,
    usedCount: 45,
    status: "disabled",
    startsAt: "2025-06-01",
    expiresAt: "2025-09-30",
  },
];

export const categories: Category[] = [
  {
    id: "cat1",
    name: "Electronics",
    slug: "electronics",
    parentId: null,
    products: 1250,
    status: "active",
    order: 1,
    attributes: ["Brand", "Warranty", "Color"],
  },
  {
    id: "cat2",
    name: "Smartphones",
    slug: "smartphones",
    parentId: "cat1",
    products: 340,
    status: "active",
    order: 1,
    attributes: ["Storage", "RAM", "OS"],
  },
  {
    id: "cat3",
    name: "Fashion",
    slug: "fashion",
    parentId: null,
    products: 2100,
    status: "active",
    order: 2,
    attributes: ["Size", "Color", "Material"],
  },
  {
    id: "cat4",
    name: "Women",
    slug: "women",
    parentId: "cat3",
    products: 1100,
    status: "active",
    order: 1,
    attributes: ["Size", "Color"],
  },
  {
    id: "cat5",
    name: "Home & Living",
    slug: "home-living",
    parentId: null,
    products: 890,
    status: "active",
    order: 3,
    attributes: ["Material", "Dimensions"],
  },
  {
    id: "cat6",
    name: "Sports",
    slug: "sports",
    parentId: null,
    products: 670,
    status: "active",
    order: 4,
    attributes: ["Size", "Sport Type"],
  },
  {
    id: "cat7",
    name: "Books",
    slug: "books",
    parentId: null,
    products: 1500,
    status: "active",
    order: 5,
    attributes: ["Author", "ISBN", "Format"],
  },
  {
    id: "cat8",
    name: "Pets",
    slug: "pets",
    parentId: null,
    products: 420,
    status: "inactive",
    order: 6,
    attributes: ["Pet Type", "Size"],
  },
];

export const cmsPages: CmsPage[] = [
  {
    id: "cms1",
    title: "About Us",
    slug: "about-us",
    status: "published",
    updatedAt: "2025-05-10",
    author: "Content Admin",
  },
  {
    id: "cms2",
    title: "Terms of Service",
    slug: "terms-of-service",
    status: "published",
    updatedAt: "2025-04-01",
    author: "Super Admin",
  },
  {
    id: "cms3",
    title: "Privacy Policy",
    slug: "privacy-policy",
    status: "published",
    updatedAt: "2025-04-01",
    author: "Super Admin",
  },
  {
    id: "cms4",
    title: "Vendor Guidelines",
    slug: "vendor-guidelines",
    status: "draft",
    updatedAt: "2025-06-20",
    author: "Content Admin",
  },
  {
    id: "cms5",
    title: "Shipping Information",
    slug: "shipping-info",
    status: "published",
    updatedAt: "2025-03-15",
    author: "Content Admin",
  },
  {
    id: "cms6",
    title: "Summer Sale Landing",
    slug: "summer-sale",
    status: "draft",
    updatedAt: "2025-06-28",
    author: "Content Admin",
  },
];

export const banners: Banner[] = [
  {
    id: "b1",
    title: "Summer Sale Hero",
    position: "Homepage Hero",
    status: "active",
    startsAt: "2025-06-01",
    endsAt: "2025-08-31",
    clicks: 12450,
    impressions: 89000,
  },
  {
    id: "b2",
    title: "New Vendor Spotlight",
    position: "Sidebar",
    status: "active",
    startsAt: "2025-06-15",
    endsAt: "2025-07-15",
    clicks: 3200,
    impressions: 45000,
  },
  {
    id: "b3",
    title: "Free Shipping Promo",
    position: "Top Bar",
    status: "scheduled",
    startsAt: "2025-08-01",
    endsAt: "2025-08-15",
    clicks: 0,
    impressions: 0,
  },
  {
    id: "b4",
    title: "Electronics Flash Deal",
    position: "Category Banner",
    status: "inactive",
    startsAt: "2025-05-01",
    endsAt: "2025-05-31",
    clicks: 8900,
    impressions: 67000,
  },
];

export const roles: Role[] = [
  {
    id: "r1",
    name: "Super Admin",
    description: "Full system access and control",
    users: 2,
    permissions: ["*"],
  },
  {
    id: "r2",
    name: "Finance Admin",
    description: "Payments, commissions, and financial reports",
    users: 4,
    permissions: [
      "payments.view",
      "payments.manage",
      "commissions.view",
      "commissions.manage",
      "reports.view",
      "reports.export",
      "orders.view",
    ],
  },
  {
    id: "r3",
    name: "Support Admin",
    description: "Customer support and order management",
    users: 8,
    permissions: [
      "customers.view",
      "customers.manage",
      "orders.view",
      "orders.manage",
      "vendors.view",
      "products.view",
    ],
  },
  {
    id: "r4",
    name: "Content Admin",
    description: "CMS, banners, and promotional content",
    users: 3,
    permissions: [
      "cms.view",
      "cms.manage",
      "banners.view",
      "banners.manage",
      "coupons.view",
      "coupons.manage",
      "categories.view",
      "categories.manage",
    ],
  },
];

export const permissions: Permission[] = [
  { id: "perm1", module: "Dashboard", actions: ["view"] },
  { id: "perm2", module: "Vendors", actions: ["view", "approve", "reject", "suspend", "manage"] },
  { id: "perm3", module: "Customers", actions: ["view", "block", "manage"] },
  { id: "perm4", module: "Products", actions: ["view", "approve", "reject", "manage"] },
  { id: "perm5", module: "Orders", actions: ["view", "manage", "refund"] },
  { id: "perm6", module: "Payments", actions: ["view", "manage"] },
  { id: "perm7", module: "Commissions", actions: ["view", "manage"] },
  { id: "perm8", module: "CMS", actions: ["view", "manage"] },
  { id: "perm9", module: "Reports", actions: ["view", "export"] },
  { id: "perm10", module: "Settings", actions: ["view", "manage"] },
  { id: "perm11", module: "Roles", actions: ["view", "manage"] },
];

export const activityLogs: ActivityLog[] = [
  {
    id: "a1",
    user: "Super Admin",
    action: "Approved vendor",
    target: "BeautyBox",
    timestamp: "2025-06-30T14:20:00",
  },
  {
    id: "a2",
    user: "Support Admin",
    action: "Blocked customer",
    target: "Carol White",
    timestamp: "2025-06-30T12:05:00",
  },
  {
    id: "a3",
    user: "Content Admin",
    action: "Published banner",
    target: "Summer Sale Hero",
    timestamp: "2025-06-30T10:30:00",
  },
  {
    id: "a4",
    user: "Finance Admin",
    action: "Updated commission",
    target: "Electronics Standard → 12%",
    timestamp: "2025-06-29T16:45:00",
  },
  {
    id: "a5",
    user: "Super Admin",
    action: "Approved product",
    target: "Wireless Noise-Canceling Headphones",
    timestamp: "2025-06-29T11:00:00",
  },
  {
    id: "a6",
    user: "Support Admin",
    action: "Processed refund",
    target: "ORD-2025-88425",
    timestamp: "2025-06-28T15:20:00",
  },
];
